"""Classify quality suspects into legitimate pairs and genuine defects.

The quality gate fails on any unwhitelisted suspect.  Whitelisting the whole
list would defeat the gate, so pairs are separated by a reproducible rule
rather than by ad-hoc judgement:

  diacritic pair  -> legitimate if BOTH members are PT dictionary words
                     (`avô`/`avó`, `pôr`/`por`, `março`/`marco` are different
                     words); otherwise one of them is a typo or an
                     orthography variant, which is a real defect
  inflected pair  -> legitimate if the base is a closed-class item
                     (`no`/`nos`, `pelo`/`pelos` are contractions, not one
                     noun counted twice); otherwise a plural that should
                     have been folded, which is a real defect

Run:  python -m scripts.make_whitelist --suspects reports/quality_suspects.tsv
Emits YAML for config.quality.whitelist_pairs plus a defect summary.
"""

from __future__ import annotations

import argparse
import csv
from collections import Counter
from pathlib import Path


def main() -> None:
    from scripts import config as config_mod
    from scripts.lemmas import pt_dictionary
    from scripts.postag import PosTagger

    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default="config.yaml")
    ap.add_argument("--suspects", required=True)
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    cfg = config_mod.load(args.config)
    vocab = pt_dictionary(cfg["lemmatizer"].get("spellchecker_lang", "pt"))
    closed = set(PosTagger.load().closed)

    with open(args.suspects, encoding="utf-8", newline="") as fh:
        rows = list(csv.DictReader(fh, delimiter="\t"))

    legit: list[tuple[str, str]] = []
    defects: list[tuple[str, str, str]] = []

    for r in rows:
        entry, other, kind = r["entry"], r["other"], r["kind"]
        if kind == "diacritic":
            if entry.lower() in vocab and other.lower() in vocab:
                legit.append((kind, f"{min(entry, other)}|{max(entry, other)}"))
            else:
                missing = entry if entry.lower() not in vocab else other
                defects.append((kind, f"{entry}|{other}", f"{missing} not a PT word"))
        elif kind == "inflected":
            if other in closed:
                legit.append((kind, f"{min(entry, other)}|{max(entry, other)}"))
            else:
                defects.append((kind, f"{entry}|{other}", f"plural of {other} not folded"))
        else:
            defects.append((kind, f"{entry}|{other}", r["detail"]))

    pairs = sorted({p for _, p in legit})
    lines = ["  whitelist_pairs:"]
    by_kind = Counter(k for k, _ in legit)
    lines.append(
        f"    # {len(pairs)} pairs accepted as legitimately distinct "
        f"({', '.join(f'{k} {v}' for k, v in sorted(by_kind.items()))})."
    )
    lines.append("    # Generated by scripts/make_whitelist.py; see that module for the rule.")
    for p in pairs:
        lines.append(f'    - "{p}"')
    text = "\n".join(lines) + "\n"

    print(text)
    print(f"--- {len(defects)} REAL DEFECTS, deliberately not whitelisted ---")
    dk = Counter(k for k, _, _ in defects)
    for k, v in sorted(dk.items()):
        print(f"  {k}: {v}")
    for kind, pair, why in defects[:25]:
        print(f"    {kind:10} {pair:28} {why}")
    if args.out:
        Path(args.out).write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
